const express=require("express"),session=require("express-session"),bcrypt=require("bcryptjs"),Database=require("better-sqlite3"),path=require("path"),fs=require("fs"),multer=require("multer");
const app=express(),db=new Database("kyoga.db"),PORT=process.env.PORT||3000;
db.exec(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,username TEXT UNIQUE,password_hash TEXT);CREATE TABLE IF NOT EXISTS articles(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,category TEXT,excerpt TEXT,content TEXT,author TEXT,image TEXT,featured INTEGER,status TEXT,created_at TEXT,updated_at TEXT,published_at TEXT)`);
if(!db.prepare("SELECT 1 FROM admins LIMIT 1").get()){let u=process.env.ADMIN_USER||"admin",p=process.env.ADMIN_PASSWORD||"ChangeMe123!";db.prepare("INSERT INTO admins(username,password_hash) VALUES(?,?)").run(u,bcrypt.hashSync(p,12));console.log("Admin:",u,"Password:",p)}
fs.mkdirSync("public/uploads",{recursive:true});const upload=multer({dest:"public/uploads/",limits:{fileSize:5e6}});
app.use(express.json({limit:"2mb"}));app.use(express.urlencoded({extended:true}));app.use(session({secret:process.env.SESSION_SECRET||"CHANGE_THIS_SECRET",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax"}}));
const auth=(q,r,n)=>q.session.adminId?n():r.status(401).json({error:"Login required"}),now=()=>new Date().toISOString();
app.get("/api/me",(q,r)=>r.json({loggedIn:!!q.session.adminId,username:q.session.username||""}));
app.post("/api/login",(q,r)=>{let a=db.prepare("SELECT * FROM admins WHERE username=?").get(q.body.username);if(!a||!bcrypt.compareSync(q.body.password,a.password_hash))return r.status(401).json({error:"Invalid login"});q.session.adminId=a.id;q.session.username=a.username;r.json({ok:true})});
app.post("/api/logout",(q,r)=>q.session.destroy(()=>r.json({ok:true})));
app.get("/api/articles",(q,r)=>{let s="SELECT * FROM articles WHERE 1=1",p=[];if(q.query.status!=="all"){s+=" AND status=?";p.push(q.query.status||"published")}if(q.query.category){s+=" AND category=?";p.push(q.query.category)}if(q.query.q){s+=" AND (title LIKE ? OR excerpt LIKE ? OR content LIKE ?)";let x="%"+q.query.q+"%";p.push(x,x,x)}s+=" ORDER BY updated_at DESC";r.json(db.prepare(s).all(...p))});
app.get("/api/articles/:id",(q,r)=>{let a=db.prepare("SELECT * FROM articles WHERE id=?").get(q.params.id);if(!a||(a.status!=="published"&&!q.session.adminId))return r.status(404).json({error:"Not found"});r.json(a)});
app.post("/api/upload",auth,upload.single("image"),(q,r)=>{if(!q.file)return r.status(400).json({error:"Image required"});r.json({url:"/uploads/"+q.file.filename})});
app.post("/api/articles",auth,(q,r)=>{let x=q.body;if(!x.title||!x.content)return r.status(400).json({error:"Headline and story are required"});let t=now(),pub=x.status==="published"?t:null;if(x.featured)db.prepare("UPDATE articles SET featured=0").run();let z=db.prepare("INSERT INTO articles(title,category,excerpt,content,author,image,featured,status,created_at,updated_at,published_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(x.title,x.category,x.excerpt||"",x.content,x.author||"Kyoga Pen",x.image||"",x.featured?1:0,x.status||"draft",t,t,pub);r.json({id:z.lastInsertRowid})});
app.put("/api/articles/:id",auth,(q,r)=>{let o=db.prepare("SELECT * FROM articles WHERE id=?").get(q.params.id),x=q.body;if(!o)return r.status(404).json({error:"Not found"});if(x.featured)db.prepare("UPDATE articles SET featured=0").run();let pub=x.status==="published"?(o.published_at||now()):null;db.prepare("UPDATE articles SET title=?,category=?,excerpt=?,content=?,author=?,image=?,featured=?,status=?,updated_at=?,published_at=? WHERE id=?").run(x.title,x.category,x.excerpt||"",x.content,x.author||"Kyoga Pen",x.image||"",x.featured?1:0,x.status,now(),pub,q.params.id);r.json({ok:true})});
app.delete("/api/articles/:id",auth,(q,r)=>{db.prepare("DELETE FROM articles WHERE id=?").run(q.params.id);r.json({ok:true})});
app.use(express.static("public"));app.get("*",(q,r)=>r.sendFile(path.resolve("public/index.html")));app.listen(PORT,()=>console.log("Kyoga Pen: http://localhost:"+PORT));